version: "2"

networks:
  app_network:
    driver: bridge

services:

  master:
    build:
      context: ../../docker-images/spark
    image: digi/spark-hdfs-node
    container_name: master
    hostname: master
    networks:
      - app_network
    ports:
      - "9870:9870" # hdfs ui
      - "54310:54310" # hdfs
      - "43211:43211" #remote intellij debugging
      - "18080:18080" #spark history ui
    volumes:
      - ./target:/target
    stdin_open: true
    tty: true
    command: bash -c "sh start-services.sh"


  worker1:
    image: digi/spark
    container_name: worker1
    hostname: worker1
    networks:
      - app_network
    ports:
      - "9861:9861"
    depends_on:
      - master
    volumes:
      - ./target:/target
    stdin_open: true
    tty: true
    command: bash -c "sh start-services.sh"


